{% set version = "1.0" %}

package:
  name: nocuda11
  version: {{ version }}


build:
  number: 0
  noarch: generic

requirements:
  run_constrained:
    - cuda-version !=11.*

test:
  commands:
    - echo "no tests for this package"

about:
  home: https://github.com/ramonaoptics/nocuda11-feedstock
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'prevents installation of cuda 11'

extra:
  recipe-maintainers:
    - hmaarrfk
